version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_tcit
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tcit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_Password1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: